version: '3.9'

services:
  nginx:
    image: byjg/nginx-extras
    volumes:
      - ./nginx/logs:/etc/nginx/logs
      - ./nginx/static:/home/static:ro
      - ./nginx/standalone:/home/standalone:ro
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/cert:/etc/nginx/cert:ro
    ports:
      - 80:80
      - 443:443
    networks: [ r1 ]
    depends_on: [ server1, server2, server3, mirror, pgadmin ]
  server1: &main-backend
    image: node:18-alpine
    environment: &server-env
      PORT: 443
      DB_TYPE: postgres
      DB_HOST: database
      DB_PORT: 5432
      DB_USERNAME: root
      DB_PASSWORD: root
      DB_DBNAME: eagool
      JWT_SECRET_KEY: 77086bf1-eb90-4475-b7d8-796e7eeaf10e
    user: node
    working_dir: /home/node/app
    volumes:
      - ./server:/home/node/app
    command: npm run start:dev
    networks: [ r1, r2 ]
    depends_on: [ database ]
  server2: &second-backend
    <<: *main-backend
    environment:
      <<: *server-env
      DB_USERNAME: root_ro
      DB_PASSWORD: root_ro
  server3:
    <<: *second-backend
  mirror:
    <<: *main-backend
    environment:
      <<: *server-env
      DB_HOST: mirrordb
    depends_on: [ mirrordb ]
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: support@eagool.com
      PGADMIN_DEFAULT_PASSWORD: root
      PGADMIN_LISTEN_PORT: 80
    networks: [ r1, r2 ]
    depends_on: [ database ]
  database: &database
    image: postgres:14-alpine
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d
      - ./db/data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: eagool
    networks: [ r2 ]
  mirrordb:
    <<: *database

networks:
  r1:
    driver: bridge
  r2:
    driver: bridge
